# Generated by Django 5.2.4 on 2025-08-03 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ilustracija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='ilustracije/', verbose_name='Slika ilustracije')),
                ('opis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Opis ilustracije')),
                ('je_vin_ilustracija', models.BooleanField(default=False, verbose_name='Je VIN ilustracija')),
                ('je_obd_ilustracija', models.BooleanField(default=False, verbose_name='Je OBD ilustracija')),
            ],
            options={
                'verbose_name': 'Ilustracija lokacije',
                'verbose_name_plural': 'Ilustracije lokacij',
            },
        ),
        migrations.CreateModel(
            name='LokacijaOpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255, unique=True, verbose_name='Opis lokacije')),
                ('je_vin_lokacija', models.BooleanField(default=False, verbose_name='Je VIN lokacija')),
                ('je_obd_lokacija', models.BooleanField(default=False, verbose_name='Je OBD lokacija')),
            ],
            options={
                'verbose_name': 'Opis lokacije',
                'verbose_name_plural': 'Opisi lokacij',
                'ordering': ['opis'],
            },
        ),
        migrations.CreateModel(
            name='TipVozila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tip vozila',
                'verbose_name_plural': 'Tipi vozil',
            },
        ),
        migrations.CreateModel(
            name='Znamka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100, unique=True)),
                ('je_popularna', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Znamka vozila',
                'verbose_name_plural': 'Znamke vozil',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255, verbose_name='Ime modela')),
                ('generacija', models.CharField(blank=True, max_length=100, null=True, verbose_name='Generacija (npr. Mk1, Mk2)')),
                ('leto_izdelave', models.IntegerField(blank=True, null=True, verbose_name='Leto izdelave modela')),
                ('tip_vozila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vozila.tipvozila', verbose_name='Tip vozila')),
                ('znamka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vozila.znamka', verbose_name='Znamka')),
            ],
            options={
                'verbose_name': 'Model avtomobila',
                'verbose_name_plural': 'Modeli avtomobilov',
                'ordering': ['znamka__ime', 'ime', 'leto_izdelave'],
                'unique_together': {('znamka', 'ime', 'generacija', 'leto_izdelave')},
            },
        ),
        migrations.CreateModel(
            name='VoziloPodrobnosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leto_od', models.IntegerField(blank=True, null=True, verbose_name='Leto izdelave od')),
                ('leto_do', models.IntegerField(blank=True, null=True, verbose_name='Leto izdelave do')),
                ('opombe', models.TextField(blank=True, null=True, verbose_name='Dodatne opombe')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vozila.carmodel', verbose_name='Model avtomobila')),
                ('ilustracija_obd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obd_podrobnosti', to='vozila.ilustracija', verbose_name='Ilustracija OBD lokacije')),
                ('ilustracija_vin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_podrobnosti', to='vozila.ilustracija', verbose_name='Ilustracija VIN lokacije')),
                ('lokacija_obd_opis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obd_lokacije', to='vozila.lokacijaopis', verbose_name='Lokacija OBD priklopa')),
                ('lokacija_vin_opis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_lokacije', to='vozila.lokacijaopis', verbose_name='Lokacija VIN številke')),
            ],
            options={
                'verbose_name': 'Podrobnosti vozila (VIN/OBD)',
                'verbose_name_plural': 'Podrobnosti vozil (VIN/OBD)',
                'ordering': ['car_model__znamka__ime', 'car_model__ime', 'leto_od'],
                'unique_together': {('car_model', 'leto_od', 'leto_do')},
            },
        ),
    ]
