# Generated by Django 5.2.4 on 2025-07-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ilustracija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='ilustracije/')),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ilustracije',
            },
        ),
        migrations.CreateModel(
            name='Znamka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Znamke',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('znamka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vozila.znamka')),
            ],
            options={
                'verbose_name_plural': 'Modeli',
                'unique_together': {('znamka', 'ime')},
            },
        ),
        migrations.CreateModel(
            name='Vozilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leto_od', models.IntegerField()),
                ('leto_do', models.IntegerField()),
                ('opombe', models.TextField(blank=True, null=True)),
                ('ilustracija_obd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vozila_obd', to='vozila.ilustracija')),
                ('ilustracija_vin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vozila_vin', to='vozila.ilustracija')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vozila.carmodel')),
                ('znamka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vozila.znamka')),
            ],
            options={
                'verbose_name_plural': 'Vozila',
                'unique_together': {('znamka', 'model', 'leto_od', 'leto_do')},
            },
        ),
    ]
