# Generated by Django 5.2.4 on 2025-07-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozila', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipVozila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi Vozil',
            },
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name_plural': 'Modeli Avtomobilov'},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='generacija',
            field=models.CharField(blank=True, help_text='Npr. Golf I, Golf II, Clio Mk1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='leto_izdelave',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ilustracija',
            name='tip_ilustracije',
            field=models.CharField(default=1, help_text="Npr. 'Osebni avto - notranjost', 'Tovornjak - motor'", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='tip_vozila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vozila.tipvozila'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('znamka', 'ime', 'generacija', 'leto_izdelave', 'tip_vozila')},
        ),
        migrations.CreateModel(
            name='VoziloPodrobnosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokacija_vin_opis', models.TextField(blank=True, help_text="Npr. 'Pod sovoznikovim sedežem, na desni strani'", null=True)),
                ('lokacija_obd_opis', models.TextField(blank=True, help_text="Npr. 'Pod armaturno ploščo, levo od volana'", null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vozila.carmodel', unique=True)),
                ('ilustracija_obd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obd_lokacije', to='vozila.ilustracija')),
                ('ilustracija_vin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_lokacije', to='vozila.ilustracija')),
            ],
            options={
                'verbose_name_plural': 'Podrobnosti Vozil (VIN/OBD)',
            },
        ),
        migrations.DeleteModel(
            name='Vozilo',
        ),
    ]
