# Generated by Django 5.2.4 on 2025-08-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vozila', '0001_initial'),
    ]

    operations = [
    ]
