# Generated by Django 5.2.4 on 2025-07-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozila', '0002_tipvozila_alter_carmodel_options_carmodel_generacija_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='car_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vozila.carmodel'),
        ),
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='ilustracija_vin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_lokacije', to='vozila.ilustracija'),
        ),
    ]
