# Generated by Django 5.2.4 on 2025-07-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozila', '0003_alter_vozilopodrobnosti_car_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['znamka__ime', 'ime', 'leto_izdelave'], 'verbose_name': 'Model avtomobila', 'verbose_name_plural': 'Modeli avtomobilov'},
        ),
        migrations.AlterModelOptions(
            name='ilustracija',
            options={'verbose_name': 'Ilustracija lokacije', 'verbose_name_plural': 'Ilustracije lokacij'},
        ),
        migrations.AlterModelOptions(
            name='tipvozila',
            options={'verbose_name': 'Tip vozila', 'verbose_name_plural': 'Tipi vozil'},
        ),
        migrations.AlterModelOptions(
            name='vozilopodrobnosti',
            options={'ordering': ['car_model__znamka__ime', 'car_model__ime', 'leto_od'], 'verbose_name': 'Podrobnosti vozila (VIN/OBD)', 'verbose_name_plural': 'Podrobnosti vozil (VIN/OBD)'},
        ),
        migrations.AlterModelOptions(
            name='znamka',
            options={'verbose_name': 'Znamka vozila', 'verbose_name_plural': 'Znamke vozil'},
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ilustracija',
            name='tip_ilustracije',
        ),
        migrations.AddField(
            model_name='vozilopodrobnosti',
            name='leto_do',
            field=models.IntegerField(blank=True, null=True, verbose_name='Velja do leta'),
        ),
        migrations.AddField(
            model_name='vozilopodrobnosti',
            name='leto_od',
            field=models.IntegerField(blank=True, null=True, verbose_name='Velja od leta'),
        ),
        migrations.AddField(
            model_name='vozilopodrobnosti',
            name='opombe',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatne opombe'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='generacija',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Generacija (npr. Mk1, Mk2)'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='ime',
            field=models.CharField(max_length=255, verbose_name='Ime modela'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='leto_izdelave',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leto izdelave modela'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='tip_vozila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vozila.tipvozila', verbose_name='Tip vozila'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='znamka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vozila.znamka', verbose_name='Znamka'),
        ),
        migrations.AlterField(
            model_name='ilustracija',
            name='opis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Opis ilustracije'),
        ),
        migrations.AlterField(
            model_name='ilustracija',
            name='slika',
            field=models.ImageField(upload_to='ilustracije/', verbose_name='Slika ilustracije'),
        ),
        migrations.AlterField(
            model_name='tipvozila',
            name='ime',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vozila.carmodel', verbose_name='Model avtomobila'),
        ),
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='ilustracija_obd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obd_podrobnosti', to='vozila.ilustracija', verbose_name='Ilustracija OBD lokacije'),
        ),
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='ilustracija_vin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_podrobnosti', to='vozila.ilustracija', verbose_name='Ilustracija VIN lokacije'),
        ),
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='lokacija_obd_opis',
            field=models.TextField(blank=True, null=True, verbose_name='Opis lokacije OBD priklopa'),
        ),
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='lokacija_vin_opis',
            field=models.TextField(blank=True, null=True, verbose_name='Opis lokacije VIN številke'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('znamka', 'ime', 'generacija', 'leto_izdelave')},
        ),
        migrations.AlterUniqueTogether(
            name='vozilopodrobnosti',
            unique_together={('car_model', 'leto_od', 'leto_do')},
        ),
    ]
