# Generated by Django 5.2.4 on 2025-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozila', '0004_alter_carmodel_options_alter_ilustracija_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='znamka',
            name='je_popularna',
            field=models.BooleanField(default=False),
        ),
    ]
