# Generated by Django 5.2.4 on 2025-07-20 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozila', '0005_znamka_je_popularna'),
    ]

    operations = [
        migrations.CreateModel(
            name='LokacijaOpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255, unique=True, verbose_name='Opis lokacije')),
            ],
            options={
                'verbose_name': 'Opis lokacije',
                'verbose_name_plural': 'Opisi lokacij',
                'ordering': ['opis'],
            },
        ),
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='leto_do',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leto izdelave do'),
        ),
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='leto_od',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leto izdelave od'),
        ),
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='lokacija_obd_opis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obd_lokacije', to='vozila.lokacijaopis', verbose_name='Lokacija OBD priklopa'),
        ),
        migrations.AlterField(
            model_name='vozilopodrobnosti',
            name='lokacija_vin_opis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_lokacije', to='vozila.lokacijaopis', verbose_name='Lokacija VIN številke'),
        ),
    ]
