# Generated by Django 5.2.4 on 2025-07-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vozila', '0006_lokacijaopis_alter_vozilopodrobnosti_leto_do_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vozilopodrobnosti',
            name='lokacija_obd_opis',
        ),
        migrations.RemoveField(
            model_name='vozilopodrobnosti',
            name='lokacija_vin_opis',
        ),
    ]
