# Generated by Django 5.2.4 on 2025-07-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozila', '0007_remove_vozilopodrobnosti_lokacija_obd_opis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vozilopodrobnosti',
            name='lokacija_obd_opis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obd_lokacije', to='vozila.lokacijaopis', verbose_name='Lokacija OBD priklopa'),
        ),
        migrations.AddField(
            model_name='vozilopodrobnosti',
            name='lokacija_vin_opis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_lokacije', to='vozila.lokacijaopis', verbose_name='Lokacija VIN številke'),
        ),
    ]
