# Generated by Django 4.2.23 on 2025-07-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozila', '0008_vozilopodrobnosti_lokacija_obd_opis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokacijaopis',
            name='je_obd_lokacija',
            field=models.BooleanField(default=False, verbose_name='Je OBD lokacija'),
        ),
        migrations.AddField(
            model_name='lokacijaopis',
            name='je_vin_lokacija',
            field=models.BooleanField(default=False, verbose_name='Je VIN lokacija'),
        ),
    ]
