# Generated by Django 4.2.23 on 2025-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozila', '0009_lokacijaopis_je_obd_lokacija_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilustracija',
            name='je_obd_ilustracija',
            field=models.BooleanField(default=False, verbose_name='Je OBD ilustracija'),
        ),
        migrations.AddField(
            model_name='ilustracija',
            name='je_vin_ilustracija',
            field=models.BooleanField(default=False, verbose_name='Je VIN ilustracija'),
        ),
    ]
